# Generated by Django 3.2.5 on 2021-08-03 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('romanji', models.CharField(max_length=155)),
                ('english', models.CharField(blank=True, max_length=155, null=True)),
                ('native', models.CharField(blank=True, max_length=155, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='title', to='animes.mediatitle')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
