# Generated by Django 3.2.5 on 2021-08-04 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0002_alter_anime_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='description',
            field=models.TextField(blank=True, default='Sinopse indisponível no momento', null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='season_year',
            field=models.DateField(null=True, verbose_name='Ano do lançamento'),
        ),
    ]
