# Generated by Django 3.2.5 on 2021-08-04 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0004_auto_20210804_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='genre',
            field=models.ManyToManyField(related_name='serie', to='animes.Genre', verbose_name='Generos'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='title',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='serie', to='animes.mediatitle'),
        ),
    ]
