# Generated by Django 3.2.5 on 2021-08-08 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0005_auto_20210804_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='format',
            field=models.IntegerField(choices=[(1, 'Tv'), (2, 'Movie'), (3, 'Ova')], null=True),
        ),
    ]
