# Generated by Django 3.2.5 on 2021-08-08 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0006_anime_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='season',
            field=models.IntegerField(choices=[(1, 'Winter'), (2, 'Spring'), (3, 'Summer'), (4, 'Fall')], null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='status',
            field=models.IntegerField(choices=[(1, 'Finished'), (2, 'Releasing')], null=True),
        ),
    ]
