# Generated by Django 3.2.5 on 2021-08-11 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0007_auto_20210808_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='image',
            field=models.ImageField(null=True, upload_to='animes'),
        ),
    ]
